### ISSUE TITLE
Non-private constants in sc_client.constants.sc_types

### ISSUE THREAD

**Issue by rastsislaux** [ostis-ai/py-sc-client#34]
**Describe the bug**
In `sc_client.constants.sc_types` there are integer constants that are not supposed to be imported. (e.g. `SC_TYPE_NODE`, `SC_TYPE_LINK`, etc.)

**Proposal**
Mark this constants as private to avoid common user from occasionally importing them.

**Comment by FalseR20** [comment]
#50 Sc types will be decomposed
