### ISSUE TITLE
Add error handling in a ScConstruction class

### ISSUE THREAD

**Issue by AlexandrZagorskiy** [ostis-ai/py-sc-client#44]
**Describe the bug**
If index by alias is not exist, error can be raised.

**To Reproduce**
![image](https://user-images.githubusercontent.com/34061914/218732243-1aab4bb7-a241-4938-b758-88de434d5f55.png)

**Expected behavior**
return None value

**Additional context**
Add error handling in a ScConstruction class, or use get() method for taking value from dict.

**Comment by FalseR20** [comment]
If there is this exception, you have an error in your code. I think it doesn't have a sence, and returning a none type will only confuse.
